#!/usr/bin/env python3
import os
import datetime as dt
from glob import glob

timestamp = dt.datetime.now().isoformat()

header = """
# This file was automatically generated by create_makefile.py, {timestamp}

.PHONY: clean
clean:
\tfind . -type f -iname '*.sif' -delete
""".strip().format(timestamp=timestamp)

template = """
.PHONY: {name}
{name}:
\tcd {name} && sudo apptainer build -F {name}.sif Apptainer
""".strip()

components = [header]

paths = glob("./*/Apptainer")
names = []
for p in sorted(paths):
    name = os.path.basename(os.path.dirname(p))
    components.append(template.format(name=name))
    names.append(name)

all_recipe = """
.PHONY: all
all: {}
""".strip().format(" ".join(names))
components.append(all_recipe)

out = "\n\n".join(components)
print(out)
