# This file was automatically generated by create_makefile.py, 2022-08-22T16:05:04.744289

.PHONY: clean
clean:
	find . -type f -iname '*.sif' -delete

.PHONY: fiji
fiji:
	cd fiji && sudo apptainer build -F fiji.sif Apptainer

.PHONY: ilastik
ilastik:
	cd ilastik && sudo apptainer build -F ilastik.sif Apptainer

.PHONY: n5-spark
n5-spark:
	cd n5-spark && sudo apptainer build -F n5-spark.sif Apptainer

.PHONY: n5mrc
n5mrc:
	cd n5mrc && sudo apptainer build -F n5mrc.sif Apptainer

.PHONY: all
all: fiji ilastik n5-spark n5mrc
