# This file was automatically generated by create_makefile.py, 2022-05-23T10:25:58.934572

.PHONY: clean
clean:
	find . -type f -iname '*.sif' -delete

.PHONY: fiji
fiji:
	cd fiji && sudo apptainer build -F fiji.sif Apptainer

.PHONY: ilastik
ilastik:
	cd ilastik && sudo apptainer build -F ilastik.sif Apptainer

.PHONY: n5-spark
n5-spark:
	cd n5-spark && sudo apptainer build -F n5-spark.sif Apptainer

.PHONY: all
all: fiji ilastik n5-spark
