name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - fiji
          - ilastik
          - n5-spark
          - n5mrc
    env:
      APPTAINER_VERSION: "1.0.2"

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
      - name: Install apptainer
        run: |
          wget https://github.com/apptainer/apptainer/releases/download/v${APPTAINER_VERSION}/apptainer_${APPTAINER_VERSION}_amd64.deb -O /tmp/apptainer.deb
          sudo dpkg -i /tmp/apptainer.deb

      - name: Build image
        run: make ${{ matrix.container }}
